### ISSUE TITLE
Java Exception in thread

### ISSUE THREAD

**Issue by FilipeOS** [MaxCamillo/android-keystore-password-recover#12]

**Comment by FilipeOS** [comment]
Sorry I'm new on this...

On 1.05 works but on 1.07 don't. Any solution?

`java -jar KeyRecover.jar -m 3 -k "XXX.jks" -d "wordlist.txt"`

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: AndroidKeystoreBrute/AndroidKeystoreBrute : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source
```

**Comment by ravensbane** [comment]
Try updating Java (JRE) to 1.8.0.

**Comment by FilipeOS** [comment]
But my Android studio don't let me choose another JDK, i ve done everything and that stupid program don't let me. Whats why I have the latest 7 version.

**Comment by ravensbane** [comment]
If you just need to run it you can update only JRE, here: http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

Additional Installation info:
https://docs.oracle.com/javase/8/docs/technotes/guides/install/install_overview.html

If that doesn't work for you I can look into recompiling it for Java 7.

**Comment by FilipeOS** [comment]
Hi,

It worked but is there a way to limit the password length? Because it's trying passwords with +20 characters...

I've tried like:
word
@
#
!
?

It's fine?

Also, this is much more slow than the v1.05

**Comment by ravensbane** [comment]
Methods 1 and 2 (Brute and Wordlist) should be equally fast as in 1.05. Method 3 is about 7x faster on systems with multiple cores (basically any desktop computer) in 1.07 than in 1.05. It might feel slower because it only notifies the user of its progress once every 5 seconds instead of once every 1 second. To see how fast it is, you need to look at the estimated number of passwords it says it's checking per second.


You can limit the number of password pieces it tries with Method 3.

**Example**
Let's say your dictionary consists of the following four words:
Apple
1234
Banana
?

You know that the password is some combination of those four words, and you know that it's not more than five words long, but you don't know exactly what it is. So the password could be "Apple" or it could be "Banana1234" or it could be "1234Apple?BananaApple". You want to check all the combinations of those words, up to a maximum of five.

To do this, you can use the "-pieces <min> <max> argument, like this:
java -jar AndroidKeystoreBrute.jar -m 3 -k "XXX.jks" -d "wordlist.txt" -pieces 1 5

Now, let's say you also knew the first few characters in the password. So you know it starts with "1!", but it could be "1!Apple?1234" or "1!Banana" or "1!Banana?Apple1234?". 

You can tell the app what these starting characters are with the "-firstchars <String>" argument, like this:
java -jar AndroidKeystoreBrute.jar -m 3 -k "XXX.jks" -d "wordlist.txt" -pieces 1 5 -firstchars 1!

Note that the first characters will not count as a separate password piece for the pieces argument. In other words, "1!AppleAppleAppleAppleApple" still counts as 5 pieces.

**Comment by FilipeOS** [comment]
Hi, issue here.

`java -jar KeyRecover.jar -m 3 -k "XXX.jks" -d "wordlist.txt" -pieces 12 16`

```
Starting smart wordlist attack on key!!
Trying variations with first letter capitalized

Firing up 8 threads
```

```
java.io.IOException: numpieces arg specifies a larger min number of pieces than resume data
        at AndroidKeystoreBrute.SmartWordlistProducer.<init>(SmartWordlistProducer.java:51)
        at AndroidKeystoreBrute.SmartWordlistPasswd.doit(SmartWordlistPasswd.java:76)
        at AndroidKeystoreBrute.AndroidKeystoreBrute.main(AndroidKeystoreBrute.java:100)
```

**Comment by ravensbane** [comment]
The app will resume where it left off if you interrupt it before it's finished checking a wordlist. As a safeguard against missing some combinations of words, it verifies that you gave it the same values for the pieces argument that it was using when it was interrupted.

The resume data is stored in the file "AndroidKeystoreBrute_Resume" in the same directory as the app. This is a text file, so you can open it up if you want to see how many pieces it was working with.

If you don't care about the resume data and just want to start over with new arguments, just delete the file "AndroidKeystoreBrute_Resume".

**Comment by FilipeOS** [comment]
Thank you!

It's possible to require a word on the middle?
For example XXWORDYY - The X and Y will change

**Comment by ravensbane** [comment]
Unfortunately it is not currently possible to specify a word in the middle. But, if you know X and Y are only a few characters you could build a dictionary like this:

**Dictionary**
WORD
A
B
..
Z
a
...
z
0
1
...
9

Then specify "-pieces 5 7" to check combinations like "WORDabcd" and "12CaWORDaC". It won't only check passwords with the format "XXWORDYY", but it will include those in the check, and a 63 word dictionary should be able to check up to 6 pieces in a reasonable amount of time.
