### ISSUE TITLE
error : java.io.IOException: not a JavaKeyStore

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MaxCamillo/android-keystore-password-recover#6]
```
What steps will reproduce the problem?
1. I hope "hogehoge.keystore" change to "newhoge.txt" for update App.

2. java -jar "C:\Users\hoge\Desktop\AndroidKeystoreBrute_v1.05.jar" -m 3 -k 
"C:\Users\hoge\Desktop\hogehoge.keystore" -d 
"C:\Users\hoge\Desktop\newhoge.txt" -w

3. command messege:
java.io.IOException: not a JavaKeyStore
        at JKS.engineLoad(JKS.java:373)
        at SmartWordlistPasswd.doit(SmartWordlistPasswd.java:64)
        at AndroidKeystoreBrute.main(AndroidKeystoreBrute.java:73)

For updates visit http://code.google.com/p/android-keystore-password-recover/

4.Is there a solution?

my PC:Windows7

Please provide any additional information below.


```

Original issue reported on code.google.com by `secimoja...@gmail.com` on 7 Aug 2014 at 7:10

**Comment by asadullazadeh** [comment]
the same issue

**Comment by yeon-kyu** [comment]
same here

**Comment by tr-appz** [comment]
Any Updates with This Issue? I have a jks file. Tried all 3 Arguments of Brute force. Same error each Time.

`java.io.IOException: not a JavaKeyStore
        at AndroidKeystoreBrute.JKS.engineLoad(JKS.java:340)
        at AndroidKeystoreBrute.BrutePasswd.doit(BrutePasswd.java:128)
        at AndroidKeystoreBrute.AndroidKeystoreBrute.main(AndroidKeystoreBrute.java:96)`

**Comment by TonyAnine** [comment]
same here

**Comment by meding09** [comment]
java.io.IOException: not a JavaKeyStore
        at AndroidKeystoreBrute.JKS.engineLoad(JKS.java:340)
        at AndroidKeystoreBrute.SmartWordlistPasswd.doit(SmartWordlistPasswd.java:40)
        at AndroidKeystoreBrute.AndroidKeystoreBrute.main(AndroidKeystoreBrute.java:100)

**Comment by konsnos** [comment]
Same here. I was using it for a keystore generated from Unity. Could it be related?
